# Generated by Django 2.2.7 on 2019-11-30 10:41

import collections
from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191130_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='attributes',
            field=jsonfield.fields.JSONField(default='{}', dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
