# Generated by Django 2.2.7 on 2019-11-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191130_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
