# Generated by Django 2.2.7 on 2019-11-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191130_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='user',
        ),
    ]
