# Generated by Django 2.2.7 on 2019-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191201_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderHash',
            new_name='hash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
