# Generated by Django 2.2.7 on 2019-12-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191201_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hash',
            new_name='orderHash',
        ),
    ]
